@startuml goodloc-usecase

left to right direction
skinparam packageStyle rectangle
skinparam monochrome true

:Visiteur: as VIS
:Utilisateur: as USR
:Admin: as ADM

rectangle "Goodloc" {
    (Demande de compte utilisateur) as demande
    
    VIS <|-up- USR
    
    VIS -- demande
    demande -- ADM
    
    VIS -- (Consulter états machines)

    USR -- (Enlever statut à controller d'une machine)
    USR -- (Charger nouveau statut machines)
}
@enduml