@startuml ouitalk-client-usecase

left to right direction
skinparam packageStyle rectangle
skinparam monochrome true
skinparam shadowing false

:Controleur: as CTRL
:Voyageur: as VOY
:Autorité Organisatrce: as OA

rectangle "Ouitalk Client" {
    (Discuter avec les autres usagers du train) as discUs
    (Inscription) as insc
    (Rechercher gare) as recGare
    (Voir départs en fonction horaires) as consDépart
    (Consulter avis) as vAvis
    (Poster avis) as pAvis
    (Demander remboursement) as demRemb
    
    VOY -- demRemb
    demRemb ---- OA
    
    VOY -- recGare
    recGare <.. consDépart : include
    consDépart <. vAvis : include
    consDépart <.left. pAvis : include
    VOY -- insc
    
    VOY -- discUs
    CTRL -- discUs
}
@enduml