@startuml zerominute-usecase

left to right direction
skinparam packageStyle rectangle
skinparam monochrome true
skinparam shadowing false

:Agent d'escale: as ASC

rectangle "Zero Minute - Declaration" {
    (Voir liste des départs à venir) as vListDep
    (Voir statistiques déclaration) as vStatDec
    (Déclarer un départ) as cDec
    (Voir historique déclaration) as vHistDec
    
    ASC -- vHistDec
    ASC -- vStatDec
    ASC -- vListDep
    
    vHistDec <.. (Modifier informations déclaration) : include
    vHistDec <.. (Voir historique modification) : include
    vListDep <.. cDec : include
}
@enduml